# Generated by Django 5.0.4 on 2024-09-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
