# Generated by Django 5.0.4 on 2024-08-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditemmodel'),
        ('order', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='FoodItemModel',
            new_name='FoodItem',
        ),
    ]
