# Generated by Django 5.0.4 on 2024-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
