# Generated by Django 5.0.4 on 2024-08-20 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_categorymodel_category_and_more'),
        ('order', '0003_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodOrderModel',
            new_name='FoodOrder',
        ),
    ]
