# Generated by Django 5.0.4 on 2024-08-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_foodordermodel_foodorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
